services:
    video_player.video_manager.default:
        class: VideoPlayerBundle\Doctrine\VideoManager
        arguments: ["security.encoder_factory", "video_player.entity_manager", "%video_player.model.video.class%"]

    video_player.entity_manager:
        factory-service: doctrine
        factory-method: getManager
        class: Doctrine\ORM\EntityManager
        arguments: ["%video_player.model_manager_name%"]