my-youtube-list-playlist:
    path:     /my-youtube-list-playlist
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:myyoutubelistplaylist }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

learn-symfony-framework:
    path:     /learn-symfony-framework
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:learnsymfonyframework }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

glossary-informatics-block:
    path:     /glossary-informatics-block
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:glossaryinformaticsblock }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

vertingo-website-introduction:
    path:     /vertingo-website-introduction
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:vertingowebsiteintroduction }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

learn-android-studio-development-and-google-play-deployment:
    path:     /learn-android-studio-development-and-google-play-deployment
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:learnandroidstudiodevelopmentandgoogleplaydeployment }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

social-blocks:
    path:     /social-blocks
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:socialblocks }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

renderpdf:
    path:     /renderpdf
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:renderpdf }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

try-my-own-google-spreadsheet:
    path:     /try-my-own-google-spreadsheet
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:trymyowngooglespreadsheet }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

build-my-own-chatbot:
    path:     /build-my-own-chatbot
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:buildmyownchatbot }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

build-my-own-vertingo-website:
    path:     /build-my-own-vertingo-website
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:buildmyownvertingowebsite }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

index-your-website-and-learn-how-to-become-well-ranked-in-search-engine:
    path:     /index-your-website-and-learn-how-to-become-well-ranked-in-search-engine
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:indexyourwebsiteandlearnhowtobecomewellrankedinsearchengine }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly   

conditions:
    path:     /conditions
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:conditions }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly   

how-to-integrate-google-data-analytics:
    path:     /how-to-integrate-google-data-analytics
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:howtointegrategoogledataanalytics }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly    
            
how-to-integrate-youtube-data-analytics:
    path:     /how-to-integrate-youtube-data-analytics
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:howtointegrateyoutubedataanalytics }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly 

download-and-install-locally:
    path:     /download-and-install-locally
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:downloadandinstalllocally }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly

testimonials:
    path:     /testimonials
    defaults: { _controller: VideoPlayerBundle:VideoPlayer:testimonials }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly