services:
    video_player.video_player_service:
        class: VideoPlayerBundle\Service\VideoPlayerService
    video_player.parser_service:
        class: VideoPlayerBundle\Service\ParserService

    video_player.twig.video_player_extension:
        class: VideoPlayerBundle\Twig\VideoPlayerExtension
        arguments: ["@video_player.video_player_service"]
        tags:
            - { name: twig.extension }