easy_admin:
    entities:
        Exemple:
            label: "Entité exemple"
            class: AppBundle\Entity\Exemple
            list:
                actions:
                    - { name: 'admin_move_up', icon: 'arrow-up', label: '', type: 'route' }
                    - { name: 'admin_move_down', icon: 'arrow-down', label: '', type: 'route' }
                fields:
                    - { property: 'media', template: ':admin/_fields:field_media.html.twig', type_options: {conf: 'default'} }
                    - { property: 'mediaCollection', template: ':admin/_fields:field_media_collection.html.twig', type_options: {conf: 'default'} }
                    - { property: 'position'}
                sort: ['position', 'ASC']
            form:
                  fields:
                        - { property: 'imageFile', type: 'file' }
                        - { property: 'media', type: 'Artgris\Bundle\MediaBundle\Form\Type\MediaType', type_options: {conf: 'default'}  }
                        - { property: 'mediaCollection', type: 'Artgris\Bundle\MediaBundle\Form\Type\MediaCollectionType', type_options: {allow_add: true, conf: 'default'} }
                        - { property: 'date', type: 'date', type_options: {widget: 'single_text', html5: false, attr: {class: 'datepicker'}, format: 'dd/MM/yyyy', required: false} }
                        - { property: 'translations', label: 'Traductions', type: 'A2lix\TranslationFormBundle\Form\Type\TranslationsType', type_options: {fields: {title: {label: 'Titre'}, content: {label: 'Contenu', attr: {class: 'tinymce'}} }} }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '/web/uploads' }