easy_admin:
    entities:
      DownloadFileCounter:
            disabled_actions: ['edit','delete','new']
            label: "DownloadFileCounter"
            #controller: AppBundle\Controller\Admin\UserController
            class: FileManagerBundle\Entity\DownloadFileCounter
#            label: 'Users'
#            help: 'Global message displayed in all views'
            list:
#                title: "%%entity_label%% listing"
#                help: 'Global message displayed in all views'
#                actions: ['show']
#                actions: ['duplicate']
                  
                  fields:
                  - 'filename'
                  - { property: 'download_counter', type: 'integer'}
                  
#                 sort: ['download_counter', 'DESC']
#                 dql_filter: 'entity.id >= 0'
            edit: #'form' is applied to both 'new' and 'edit' views
                fields:
                  - 'filename'
                  - { property: 'download_counter', type: 'integer'}
                  