easy_admin:
    entities:
        FootballAPI:
            disabled_actions: ['delete']
            label: "FootballAPI"
          #  controller: VideoPlayerBundle\Controller\Admin\UserController
            class: AppBundle\Entity\FootballAPI
#            label: 'Users'
#            help: 'Global message displayed in all views'
            list:
#                title: "%%entity_label%% listing"
#                help: 'Global message displayed in all views'
#                actions: ['show']
#                actions: ['duplicate']
                fields:
                  - { property: 'championnat_favori', template: 'admin/_fields/field_role.html.twig', label_colors: {'Ligue 1' : 'primary', 'BundesLiga' : 'primary', 'Liga' : 'primary', 'Premier League' : 'primary'}}
                  - { property: 'joueur_favori', template: 'admin/_fields/field_role.html.twig', label_colors: {'Lionel Messi' : 'primary', 'Karim Benzema' : 'primary', 'Kylian Mbappé' : 'primary'}}
                  - { property: 'club_favori', template: 'admin/_fields/field_role.html.twig', label_colors: {'Real-Madrid' : 'primary', 'Barcelone' : 'primary', 'Chelsea' : 'primary'}}
                  - 'username'
            
#                sort: 'createdAt'
#                dql_filter: 'entity.id >= 0'
            form: #'form' is applied to both 'new' and 'edit' views
                fields:
                    - { property: 'championnat_favori', type: 'choice', type_options: { multiple: true, attr: { data-widget: 'select2' }, choices: { 'Ligue 1': 'Ligue 1', 'BundesLiga': 'BundesLiga', 'Liga': 'Liga', 'Premier League': 'Premier League'}} }
                    - { property: 'joueur_favori', type: 'choice', type_options: { multiple: true, attr: { data-widget: 'select2' }, choices: { 'Lionel Messi': 'Lionel Messi', 'Karim Benzema': 'Karim Benzema', 'Kylian Mbappé': 'Kylian Mbappé' }} }
                    - { property: 'club_favori', type: 'choice', type_options: { multiple: true, attr: { data-widget: 'select2' }, choices: { 'Real-Madrid': 'Real-Madrid', 'Barcelone': 'Barcelone', 'Chelsea': 'Chelsea' }} }
                    - 'username'
                    

                    
                   