easy_admin:
    entities:
        Video:
            disabled_actions: ['edit','new','delete']
            label: "Video"
          #  controller: VideoPlayerBundle\Controller\Admin\UserController
            class: VideoPlayerBundle\Entity\MainVideo
#            label: 'Users'
#            help: 'Global message displayed in all views'
            list:
#                title: "%%entity_label%% listing"
#                help: 'Global message displayed in all views'
#                actions: ['show']
#                actions: ['duplicate']
                fields:
                  - 'title'
                  - 'video_url'
                  #- { property: 'video_server', type: 'integer'}
                  - { property: 'thumb', type: 'image'}
                  - 'description'
                  - { property: 'enabled', type: 'toggle'}
                  
                
#                sort: 'createdAt'
#                dql_filter: 'entity.id >= 0'
            form: #'form' is applied to both 'new' and 'edit' views
                fields:
                    - 'title'
                    - 'video_url'
                    #- { property: 'video_server', type: 'integer'}
                    - { property: 'thumb', type: 'image'}
                    - 'description'
                    - { property: 'enabled', type: 'toggle'}

                    
                   