easy_admin:
    entities:
        YouTubeInfos:
            disabled_actions: ['delete','edit','new']
            label: "YouTubeInfos"
          #  controller: VideoPlayerBundle\Controller\Admin\UserController
            class: VideoPlayerBundle\Entity\YouTubeInfos
#            label: 'Users'
#            help: 'Global message displayed in all views'
            list:
#                title: "%%entity_label%% listing"
#                help: 'Global message displayed in all views'
#                actions: ['show']
#                actions: ['duplicate']
                fields:
                  - 'idyoutube'
                  - 'titleyoutube'
                  - 'subscribercount'
                  - 'viewcount'
                  - 'videocount'
                  - 'channeldescription'
                  - 'customurl'
                  - 'username'
                    
#                sort: 'createdAt'
#                dql_filter: 'entity.id >= 0'
            form: #'form' is applied to both 'new' and 'edit' views
                fields:
                  - 'idyoutube'
                  - 'titleyoutube'
                  - 'subscribercount'
                  - 'viewcount'
                  - 'videocount'
                  - 'channeldescription'
                  - 'customurl'
                  - 'username'

                    
                   