imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                url: "%database_url%"
                host:     "%database_host_prod%"
                port:     "%database_port_prod%"
                dbname:   "%database_name_prod%"
                user:     "%database_user_prod%"
                password: "%database_password_prod%"
                charset:  UTF8
            mandantA:
                driver:   %database_driver_mandanta_prod%
                url: "%database_url2%"
                host:     %database_host_mandanta_prod%
                port:     %database_port_mandanta_prod%
                dbname:   %database_name_mandanta_prod%
                user:     %database_user_mandanta_prod%
                password: %database_password_mandanta_prod%
                charset:  UTF8
            mandantB:
                driver:   %database_driver_mandantb_prod%
                url: "%database_url3%"
                host:     %database_host_mandantb_prod%
                port:     %database_port_mandantb_prod%
                dbname:   %database_name_mandantb_prod%
                user:     %database_user_mandantb_prod%
                password: %database_password_mandantb_prod%
        types:
            media: Artgris\Bundle\MediaBundle\Type\MediaType
            media_collection: Artgris\Bundle\MediaBundle\Type\MediaCollectionType
            json: Sonata\Doctrine\Types\JsonType
            nostreamblob: Ibrows\Bundle\NewsletterBundle\DBAL\Types\NoStreamBlobType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        # path:     "%database_path%"

    orm:
        entity_managers:
                default:
                    connection: default
                    mappings:
                        AppBundle: ~
                    #FOSUserBundle: ~
                    #ApplicationSonataMediaBundle: ~
                    #SonataMediaBundle: ~
                    #SonataClassificationBundle: ~
                mandantA:
                    connection: mandantA
                    mappings:
                        ibrows_newsletter:
                            type: annotation
                            prefix: AppBundle\Entity\Newsletter
                            dir: "%kernel.root_dir%/../src/AppBundle/Entity/Newsletter"
                            is_bundle: false
                mandantB:
                    connection: mandantB
                    mappings:
                        ibrows_newsletter:
                            type: annotation
                            prefix: AppBundle\Entity\Newsletter
                            dir: "%kernel.root_dir%/../src/AppBundle/Entity/Newsletter"
                            is_bundle: false

youwe_file_manager:
    upload_path: %kernel.root_dir%/../../web/uploads
    full_exception: false
    theme:
        css: "/bundles/youwefilemanager/css/simple/default.css"
        template: "YouweFileManagerBundle:FileManager:file_manager.html.twig"
    mime_allowed:
        - 'image/png'
        - 'image/jpg'
        - 'image/jpeg'
        - 'image/gif'
        - 'application/pdf'
        - 'application/ogg'
        - 'video/mp4'
        - 'application/zip'
        - 'multipart/x-zip'
        - 'application/rar'
        - 'application/x-rar-compressed'
        - 'application/x-zip-compressed'
        - 'application/tar'
        - 'application/x-tar'
        - 'text/plain'
        - 'text/x-asm'
        - 'application/octet-stream'

