app:
    resource: '@AppBundle/Controller/'
#   type: annotation

easy_admin_bundle:
    resource: "@AppBundle/Controller/Admin/AdminController.php"
    type:     annotation
    options: { i18n: false }
    prefix:   /admin

presta_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

front_bundle_file_manager:
    resource: "@FileManagerBundle/Resources/config/routing.yml"

front_video_player_bundle:
    resource: "@VideoPlayerBundle/Resources/config/routing.yml"

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type: annotation
    prefix: /admin/_trans

youwe_file_manager:
    resource: "@YouweFileManagerBundle/Resources/config/routing.yml"
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

feedrss:
   resource: "@AppBundle/Resources/config/routing.yml"

app_liste_medias:
        resource: "@AppBundle/Resources/config/routing/exemple.yml"
        prefix:   /liste_medias

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

artgris_media:
    resource: "@ArtgrisMediaBundle/Resources/config/routing.yml"

block:
   resource: "@ArkounayBlockI18nBundle/Resources/config/routing.yml"

#app/config/routing.yml

usn_newsletter:
    resource: "@NewsletterBundle/Resources/config/routing.yml"

oneup_uploader:
    resource: .
    type: uploader

newsletters:
    resource: "@NewslettersBundle/Controller/"
    type:     annotation
    prefix:   /newsletters

newsletters_admin:
    path:     admin/tools/newsletters
    defaults: { _controller: NewslettersBundle:Newsletter:list }

newsletters_admin2:
    path:     newsletters
    defaults: { _controller: NewslettersBundle:Newsletter:list }

#_novaezseoRoutes:
    # resource: "@NovaeZSEOBundle/Controller/"
    # type:     annotation
    # prefix:   /

#ibrows_newsletter:
    #resource: "@IbrowsNewsletterBundle/Controller/"
    #type:     annotation
    #prefix:   /newsletter


#_liip_imagine:
#    resource: "@LiipImagineBundle/Resources/config/routing.xml"

#sitemaps:
    #prefix: /sitemaps
    #resource: "@CmfSeoBundle/Resources/config/routing/sitemap.xml"