VideoPlayerBundle\Entity\Video:
    type: mappedSuperclass
    #repositoryClass: VideoRepository
    table: video
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
        videoId:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        videoUrl:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        videoServer:
            type: integer
            nullable: false
        thumb:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        enabled:
            type: boolean
            nullable: true
            length: 100
            fixed: false
            comment: ''
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
