liste_medias:
    path:  /
    defaults: { _controller: "AppBundle:Exemple:index" }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly
            lastmod: now

liste_medias_show:
    path:  /{id}/show
    defaults: { _controller: "AppBundle:Exemple:show" }
    options:
        sitemap:
            priority: 0.5
            changefreq: weekly
            lastmod: now



