NewsletterBundle\Entity\Newsletter:
  type: entity
  table: newsletter
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    email:
      type: string
      length: 255
    access_key:
      type: string
      length: 255
    created_at:
      type: datetime
  uniqueConstraints:
    email_idx:
      columns: email
  lifecycleCallbacks:
    prePersist: [ setCreatedAtToNow, generateAccessKey ]
