app_medias:
    resource: "@AppBundle/Resources/config/routing/exemple.yml"
    prefix:   /medias


feed:
    path:     flux_rss_vertin_go_prod
    defaults: { _controller: AppBundle:VertinGoFeedController:feed }
    options:
        sitemap:
            priority: 0.7
            changefreq: weekly
    

register:
    path:     /register_app_mobile
    defaults: { _controller: AppBundle:Register:register }
    
            
insertid:
    path:     insertyoutube
    defaults: { _controller: AppBundle:InsertYouTube:insertid }

insertanalytics:
    path:     insertyoutubeanalytics
    defaults: { _controller: AppBundle:InsertYouTube:insertanalytics }

appmobileregister:
    path:     /appmobileregister
    defaults: { _controller: AppBundle:AppMobileRegister:appmobileregister }
