
interactive:
    resource: "@FileManagerBundle/Controller/ManagerController.php"
    type:     annotation

index:
    path:     front_file_manager/
    defaults: { _controller: FileManagerBundle:Manager:index2 }
    
    
front_bundle_file_manager:
    path:     /admin/tools/manager
    defaults: { _controller: FileManagerBundle:Manager:index }    


#front_bundle_file_manager:
   # resource: "@FileManagerBundle/Controller/ManagerController.php"
   # type:     annotation
   # prefix: /admin/tools/manager

upload_file:
    path:     upload
    defaults: { _controller: FileManagerBundle:ManagerController:uploadFile }

binary_file_response:
    path:     /binaryFileResponse
    defaults: { _controller: FileManagerBundle:ManagerController:binaryFileResponse }