name: Symfony CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo, sqlite

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction

      - name: Run tests
        run: |
          ./vendor/bin/phpunit --coverage-text

      - name: Check code style
        run: |
          ./vendor/bin/phpcs

      - name: Build cache
        run: |
          ./bin/console cache:clear --no-warmup

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to production server..."
          # Add your deployment script or commands here

